<?php

namespace TwitterSearch\Search;
use \Mockery as m;


/**
 * Test class for Client.
 * Generated by PHPUnit on 2011-06-17 at 23:03:45.
 */
class ClientTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Client
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @todo Implement testGetTweets().
     */
    public function testGetTweets()
    {
        $mockHttp = m::mock('\Zend_Http_Client');

        $client = new Client($mockHttp);

        $tweets = $client->getTweets('microsoft', 2);

        $expectedTweets = array(array('text' => 'test'));

        $this->assertEquals($expectedTweets, $tweets);
    }

    public function testGetTweetsMultiplePages()
    {
        $this->markTestIncomplete();
    }

}

?>
